language: csharp
dist: xenial
services: docker
sudo: required
mono: none
dotnet: 2.2.105
before_install:
  - docker-compose up -d
script:
  - dotnet restore RedisSlimClient.sln
  - dotnet build RedisSlimClient.sln
  - dotnet test tests/RedisSlimClient.Tests/RedisSlimClient.UnitTests.csproj --filter TestCategory!=BuildOmit
  - dotnet test tests/RedisSlimClient.IntegrationTests/RedisSlimClient.IntegrationTests.csproj --filter TestCategory!=BuildOmit
after_script:
  - docker-compose down