language: csharp
dist: xenial
services: docker
sudo: required
mono: none
dotnet: 3.1
before_install:
  - docker-compose up -d
  - sleep 10
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test tests/RedisTribute.Tests/RedisTribute.UnitTests.csproj --filter TestCategory!=BuildOmit
  - dotnet test tests/RedisTribute.IntegrationTests/RedisTribute.IntegrationTests.csproj --filter TestCategory!=BuildOmit --verbosity n 
after_script:
  - docker-compose down