language: csharp
dist: xenial
services: docker
sudo: required
mono: none
dotnet: 2.2.105
before_install:
  - docker-compose up -d
  - sleep 5
script:
  - dotnet restore RedisTribute.sln
  - dotnet build RedisTribute.sln
  - dotnet test tests/RedisTribute.Tests/RedisTribute.UnitTests.csproj --filter TestCategory!=BuildOmit
  - dotnet test tests/RedisTribute.IntegrationTests/RedisTribute.IntegrationTests.csproj --filter TestCategory!=BuildOmit --verbosity n 
after_script:
  - docker-compose down