version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./RedisSlimClient.sln --verbosity m
build_script:
  - cmd: dotnet build ./RedisSlimClient.sln
after_build:
test_script:
  - cmd: dotnet test ./tests/RedisSlimClient.Tests/RedisSlimClient.UnitTests.csproj --filter TestCategory!=BuildOmit