version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src/RedisSlimClient/RedisSlimClient.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./src/RedisSlimClient/RedisSlimClient.csproj
after_build:
clone_depth: 1
test_script:
  - cmd: dotnet restore ./tests/RedisSlimClient.Tests/RedisSlimClient.Tests.csproj --verbosity m
  - cmd: cd tests
  - cmd: dotnet xunit
on_finish :
deploy: off
build:
  verbosity: minimal