version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
before_build:
  - cmd: docker run -d -p 6379:6379 --name redis-local redis
  - cmd: dotnet --version
  - cmd: dotnet restore ./RedisSlimClient.sln --verbosity m
build_script:
  - cmd: dotnet publish ./RedisSlimClient.sln
after_build:
test_script:
  - cmd: dotnet test