version: "3"

services:
 redis1:
  image: redis:alpine
  container_name: redisharness-1
  networks:
   - net1
 app1:
  build: 
   context: .
  container_name: app-1
  command: [ "dotnet", "run", "--", "redis1:6379" ]
  networks:
   - net1
volumes:
 redis-drive:
networks:
 net1: