version: "3"

services:
 redis1:
  image: redis:alpine
  container_name: redisci-1
  ports:
   - "9096:6379"
  networks:
   - net1
 
 redis-master1:
  image: redis:alpine
  command: redis-server --port 6376
  container_name: redis-master1
  ports:
   - "9196:6376"
  networks:
   - net1
 
 redis-slave1:
  image: redis:alpine
  command: redis-server --port 6377 --slaveof redis-master1 6376
  container_name: redis-slave1
  ports:
   - "9194:6377"
  networks:
   - net1
  depends_on:
   - redis-master1
 
 redis-slave2:
  image: redis:alpine
  command: redis-server --port 6378 --slaveof redis-master1 6376
  container_name: redis-slave2
  ports:
   - "9195:6378"
  networks:
   - net1
  depends_on:
   - redis-master1

 # See https://github.com/Grokzen/docker-redis-cluster
 redis-cluster:
  image: grokzen/redis-cluster
  environment:
    STANDALONE: 'true'
    IP: 0.0.0.0
  ports:
   - "7000:7000"
   - "7001:7001"
   - "7002:7002"
   - "7003:7003"
   - "7004:7004"
   - "7005:7005"
  networks: 
   - cluster-net

 redis-ssl1:
  container_name: redisssl-1
  build:
      context: ./build/stunnel
      dockerfile: Dockerfile
  command: stunnel /stunnel/stunnel1.conf
  environment:
      redis_host: redis1
  links: 
    - redis1
  ports:
    - "6380:6380"
  networks:
   - net1
  depends_on:
   - redis1

volumes:
 redis-drive:
networks:
 net1:
 cluster-net: